name: Javadoc
on:
  push:
    branches:
      - master
      - javadocs

permissions:
  contents: write

jobs:
  javadocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: setup
      - name: Javadoc with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: :javadoc :test
      - name: clone pages branch
        uses: actions/checkout@v3
        with:
          ref: gh_pages
          path: githubPage
      - name: Delete old
        run: rm -rf githubPage/master/*
      - name: make javadoc folder
        run: mkdir -p githubPage/master/javadocs
      - name: make code coverage folder
        run: mkdir -p githubPage/master/codecoverage
      - name: move javadocs
        run: mv build/docs/javadoc/* githubPage/master/javadocs
      - name: move code coverage
        run: mv build/reports/jacoco/test/html/* githubPage/master/codecoverage
      - name: push to branch
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'gh_pages'
          directory: githubPage

